FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache bash

# Copiar package.json y package-lock.json primero para cache
COPY package*.json ./

RUN npm install

# Copiar el resto del código del frontend
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

